//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTC {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AboutBox1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AboutBox1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VTC.AboutBox1", typeof(AboutBox1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.DockStyle similar to Fill.
        /// </summary>
        public static System.Windows.Forms.DockStyle labelCompanyName_Dock {
            get {
                object obj = ResourceManager.GetObject("labelCompanyName.Dock", resourceCulture);
                return ((System.Windows.Forms.DockStyle)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=185,Y=78}.
        /// </summary>
        public static System.Drawing.Point labelCompanyName_Location {
            get {
                object obj = ResourceManager.GetObject("labelCompanyName.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.Padding similar to {Left=6,Top=0,Right=3,Bottom=0}.
        /// </summary>
        public static System.Windows.Forms.Padding labelCompanyName_Margin {
            get {
                object obj = ResourceManager.GetObject("labelCompanyName.Margin", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=0, Height=17}.
        /// </summary>
        public static System.Drawing.Size labelCompanyName_MaximumSize {
            get {
                object obj = ResourceManager.GetObject("labelCompanyName.MaximumSize", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=355, Height=17}.
        /// </summary>
        public static System.Drawing.Size labelCompanyName_Size {
            get {
                object obj = ResourceManager.GetObject("labelCompanyName.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 22.
        /// </summary>
        public static int labelCompanyName_TabIndex {
            get {
                object obj = ResourceManager.GetObject("labelCompanyName.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License GPLv3.
        /// </summary>
        public static string labelCompanyName_Text {
            get {
                return ResourceManager.GetString("labelCompanyName.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.ContentAlignment similar to MiddleLeft.
        /// </summary>
        public static System.Drawing.ContentAlignment labelCompanyName_TextAlign {
            get {
                object obj = ResourceManager.GetObject("labelCompanyName.TextAlign", resourceCulture);
                return ((System.Drawing.ContentAlignment)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.DockStyle similar to Fill.
        /// </summary>
        public static System.Windows.Forms.DockStyle labelCopyright_Dock {
            get {
                object obj = ResourceManager.GetObject("labelCopyright.Dock", resourceCulture);
                return ((System.Windows.Forms.DockStyle)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=185,Y=52}.
        /// </summary>
        public static System.Drawing.Point labelCopyright_Location {
            get {
                object obj = ResourceManager.GetObject("labelCopyright.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.Padding similar to {Left=6,Top=0,Right=3,Bottom=0}.
        /// </summary>
        public static System.Windows.Forms.Padding labelCopyright_Margin {
            get {
                object obj = ResourceManager.GetObject("labelCopyright.Margin", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=0, Height=17}.
        /// </summary>
        public static System.Drawing.Size labelCopyright_MaximumSize {
            get {
                object obj = ResourceManager.GetObject("labelCopyright.MaximumSize", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=355, Height=17}.
        /// </summary>
        public static System.Drawing.Size labelCopyright_Size {
            get {
                object obj = ResourceManager.GetObject("labelCopyright.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 21.
        /// </summary>
        public static int labelCopyright_TabIndex {
            get {
                object obj = ResourceManager.GetObject("labelCopyright.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright Zlatko Babić, 2014.
        /// </summary>
        public static string labelCopyright_Text {
            get {
                return ResourceManager.GetString("labelCopyright.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.ContentAlignment similar to MiddleLeft.
        /// </summary>
        public static System.Drawing.ContentAlignment labelCopyright_TextAlign {
            get {
                object obj = ResourceManager.GetObject("labelCopyright.TextAlign", resourceCulture);
                return ((System.Drawing.ContentAlignment)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.DockStyle similar to Fill.
        /// </summary>
        public static System.Windows.Forms.DockStyle labelProductName_Dock {
            get {
                object obj = ResourceManager.GetObject("labelProductName.Dock", resourceCulture);
                return ((System.Windows.Forms.DockStyle)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=185,Y=0}.
        /// </summary>
        public static System.Drawing.Point labelProductName_Location {
            get {
                object obj = ResourceManager.GetObject("labelProductName.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.Padding similar to {Left=6,Top=0,Right=3,Bottom=0}.
        /// </summary>
        public static System.Windows.Forms.Padding labelProductName_Margin {
            get {
                object obj = ResourceManager.GetObject("labelProductName.Margin", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=0, Height=17}.
        /// </summary>
        public static System.Drawing.Size labelProductName_MaximumSize {
            get {
                object obj = ResourceManager.GetObject("labelProductName.MaximumSize", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=355, Height=17}.
        /// </summary>
        public static System.Drawing.Size labelProductName_Size {
            get {
                object obj = ResourceManager.GetObject("labelProductName.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 19.
        /// </summary>
        public static int labelProductName_TabIndex {
            get {
                object obj = ResourceManager.GetObject("labelProductName.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video Transcoder and Converter.
        /// </summary>
        public static string labelProductName_Text {
            get {
                return ResourceManager.GetString("labelProductName.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.ContentAlignment similar to MiddleLeft.
        /// </summary>
        public static System.Drawing.ContentAlignment labelProductName_TextAlign {
            get {
                object obj = ResourceManager.GetObject("labelProductName.TextAlign", resourceCulture);
                return ((System.Drawing.ContentAlignment)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.DockStyle similar to Fill.
        /// </summary>
        public static System.Windows.Forms.DockStyle labelVersion_Dock {
            get {
                object obj = ResourceManager.GetObject("labelVersion.Dock", resourceCulture);
                return ((System.Windows.Forms.DockStyle)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=185,Y=26}.
        /// </summary>
        public static System.Drawing.Point labelVersion_Location {
            get {
                object obj = ResourceManager.GetObject("labelVersion.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.Padding similar to {Left=6,Top=0,Right=3,Bottom=0}.
        /// </summary>
        public static System.Windows.Forms.Padding labelVersion_Margin {
            get {
                object obj = ResourceManager.GetObject("labelVersion.Margin", resourceCulture);
                return ((System.Windows.Forms.Padding)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=0, Height=17}.
        /// </summary>
        public static System.Drawing.Size labelVersion_MaximumSize {
            get {
                object obj = ResourceManager.GetObject("labelVersion.MaximumSize", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=355, Height=17}.
        /// </summary>
        public static System.Drawing.Size labelVersion_Size {
            get {
                object obj = ResourceManager.GetObject("labelVersion.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 0.
        /// </summary>
        public static int labelVersion_TabIndex {
            get {
                object obj = ResourceManager.GetObject("labelVersion.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version 1.2.0.
        /// </summary>
        public static string labelVersion_Text {
            get {
                return ResourceManager.GetString("labelVersion.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.ContentAlignment similar to MiddleLeft.
        /// </summary>
        public static System.Drawing.ContentAlignment labelVersion_TextAlign {
            get {
                object obj = ResourceManager.GetObject("labelVersion.TextAlign", resourceCulture);
                return ((System.Drawing.ContentAlignment)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.DockStyle similar to Fill.
        /// </summary>
        public static System.Windows.Forms.DockStyle logoPictureBox_Dock {
            get {
                object obj = ResourceManager.GetObject("logoPictureBox.Dock", resourceCulture);
                return ((System.Windows.Forms.DockStyle)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap logoPictureBox_Image {
            get {
                object obj = ResourceManager.GetObject("logoPictureBox.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=3,Y=3}.
        /// </summary>
        public static System.Drawing.Point logoPictureBox_Location {
            get {
                object obj = ResourceManager.GetObject("logoPictureBox.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=173, Height=259}.
        /// </summary>
        public static System.Drawing.Size logoPictureBox_Size {
            get {
                object obj = ResourceManager.GetObject("logoPictureBox.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.PictureBoxSizeMode similar to StretchImage.
        /// </summary>
        public static System.Windows.Forms.PictureBoxSizeMode logoPictureBox_SizeMode {
            get {
                object obj = ResourceManager.GetObject("logoPictureBox.SizeMode", resourceCulture);
                return ((System.Windows.Forms.PictureBoxSizeMode)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 12.
        /// </summary>
        public static int logoPictureBox_TabIndex {
            get {
                object obj = ResourceManager.GetObject("logoPictureBox.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.AnchorStyles similar to Bottom, Right.
        /// </summary>
        public static System.Windows.Forms.AnchorStyles okButton_Anchor {
            get {
                object obj = ResourceManager.GetObject("okButton.Anchor", resourceCulture);
                return ((System.Windows.Forms.AnchorStyles)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=465,Y=239}.
        /// </summary>
        public static System.Drawing.Point okButton_Location {
            get {
                object obj = ResourceManager.GetObject("okButton.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=75, Height=23}.
        /// </summary>
        public static System.Drawing.Size okButton_Size {
            get {
                object obj = ResourceManager.GetObject("okButton.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 24.
        /// </summary>
        public static int okButton_TabIndex {
            get {
                object obj = ResourceManager.GetObject("okButton.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;OK.
        /// </summary>
        public static string okButton_Text {
            get {
                return ResourceManager.GetString("okButton.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=182,Y=107}.
        /// </summary>
        public static System.Drawing.Point richTextBoxDescription_Location {
            get {
                object obj = ResourceManager.GetObject("richTextBoxDescription.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=358, Height=126}.
        /// </summary>
        public static System.Drawing.Size richTextBoxDescription_Size {
            get {
                object obj = ResourceManager.GetObject("richTextBoxDescription.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 25.
        /// </summary>
        public static int richTextBoxDescription_TabIndex {
            get {
                object obj = ResourceManager.GetObject("richTextBoxDescription.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string richTextBoxDescription_Text {
            get {
                return ResourceManager.GetString("richTextBoxDescription.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 2.
        /// </summary>
        public static int tableLayoutPanel_ColumnCount {
            get {
                object obj = ResourceManager.GetObject("tableLayoutPanel.ColumnCount", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.DockStyle similar to Fill.
        /// </summary>
        public static System.Windows.Forms.DockStyle tableLayoutPanel_Dock {
            get {
                object obj = ResourceManager.GetObject("tableLayoutPanel.Dock", resourceCulture);
                return ((System.Windows.Forms.DockStyle)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.TableLayoutSettings.
        /// </summary>
        public static System.Windows.Forms.TableLayoutSettings tableLayoutPanel_LayoutSettings {
            get {
                object obj = ResourceManager.GetObject("tableLayoutPanel.LayoutSettings", resourceCulture);
                return ((System.Windows.Forms.TableLayoutSettings)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=9,Y=9}.
        /// </summary>
        public static System.Drawing.Point tableLayoutPanel_Location {
            get {
                object obj = ResourceManager.GetObject("tableLayoutPanel.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 6.
        /// </summary>
        public static int tableLayoutPanel_RowCount {
            get {
                object obj = ResourceManager.GetObject("tableLayoutPanel.RowCount", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=543, Height=265}.
        /// </summary>
        public static System.Drawing.Size tableLayoutPanel_Size {
            get {
                object obj = ResourceManager.GetObject("tableLayoutPanel.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 0.
        /// </summary>
        public static int tableLayoutPanel_TabIndex {
            get {
                object obj = ResourceManager.GetObject("tableLayoutPanel.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
    }
}
